base_config: configs/twc_bcy_f_full.yaml
output:
  experiment_name: twc_bcz_f10_full_bundle
twc:
  eval:
    fs_in_target_db_values:
    - -10.0
  unfolded:
    train_fs_in_target_db_values:
    - -10.0
